server:
  port: 8002
  domain: https://k10a709.p.ssafy.io
  servlet:
    contextPath: "/api/game-service"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: game-service
  devtools:
    livereload:
      enabled: true

#logging
logging:
  level:
    org:
      springframework:
        messaging: INFO
        web:
          socket: INFO
      hibernate.orm.jdbc.bind: TRACE
    com.s10p31a709.game.common.aop: INFO

game:
  time:
    waiting: 10
    hide: 30
    seek: 90
    result: 10
  maxCapacity: 6
  object:
    maxSeekerIdx: 14
    maxHiderIdx: 20
  fps: 20
