version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - game_service
      - member_service
      - frontend
    restart: always

  member_service:
    build:
      context: ./backend/member_service
      dockerfile: Dockerfile
    image: choichangho514/backend_member_service
    ports:
      - "8001:8001"
    restart: always

  game_service:
    build:
      context: ./backend/game_service
      dockerfile: Dockerfile
    image: choichangho514/backend_game_service
    ports:
      - "8002:8002"
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: choichangho514/frontend
    ports:
      - "8081:80"
    restart: always

networks:
  default:
    driver: bridge
