server:
  port: 8001
  domain: https://k10a709.p.ssafy.io
  servlet:
    contextPath: "/api/member-service"
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: member-service
  devtools:
    livereload:
      enabled: true
  datasource: 
#    hikari:
#      driver-class-name: org.mariadb.jdbc.Driver
#      username: S10P31A709
#      password: 2xAVwVzvO7
#    url: jdbc:mariadb://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S10P31A709?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      username: bum
      password: 12rlawhdqja!21
    url: jdbc:mariadb://database.cfsgaygiae4v.ap-northeast-2.rds.amazonaws.com:3306/s10p31a709

  # jpa
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        #        show-sql: true
        format_sql: true
#      open-in-view: false

#logging
logging:
  level:
    org:
      springframework.web: DEBUG
      hibernate.orm.jdbc.bind: TRACE
    com.s10p31a709.member.aop: TRACE
