---
## Default Elasticsearch configuration from Elasticsearch base image.
## https://github.com/elastic/elasticsearch/blob/main/distribution/docker/src/docker/config/elasticsearch.yml
#
cluster.name: docker-cluster
network.host: 0.0.0.0

## X-Pack settings
## see https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html
#
xpack.license.self_generated.type: basic
xpack.security.enabled: false
#xpack.monitoring.collection.enabled: false
#xpack.monitoring.enabled: false
#xpack.monitoring.elasticsearch.username: logstash_internal
#xpack.monitoring.elasticsearch.password: changeme
#


#xpack.security:
#  enabled: true
#  transport:
#    ssl:
#      enabled: true #xpack.security 옵션을 활성화 해주면서 xpack.security.transport.ssl 옵션도 활성화 필요
